# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

scan_timeout = 10

[username]
style_user = 'blue bold'
style_root = 'red bold'
format = '[$user]($style) in '
disabled = false
show_always = true

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[❯](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'
error_symbol = "[❯](red)"

[git_branch]
symbol = " "
format = "[$symbol$branch]($style) "
style = "blue bold"

[directory]
style = "purple bold"
read_only = " "
truncation_length = 4
truncate_to_repo = true

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true


